### ISSUE TITLE
Cross-validation with weights/offset

### ISSUE THREAD

**Issue by nizimmer** [dajmcdon/sparsegl#44]
Hello,
thank you for your speedy implementation of the Sparse Group Lasso. 

I have difficulties using weights in the `cv.sparsegl` function. Here is a MWE:
```
library("sparsegl")
set.seed(1010)
n <- 100
p <- 200
X <- matrix(data = rnorm(n * p, mean = 0, sd = 0.2), nrow = n, ncol = p)
beta_star <- c(rep(5, 5), c(5, -5, 2, 0, 0), 
               rep(-5, 5), c(2, -3, 8, 0, 0), rep(0, (p - 20)))
mu <- exp(X %*% beta_star)
y <- sapply(mu, function(x)rpois(1, x))
groups <- rep(1:(p / 5), each = 5)
weights <- runif(n) 

fit <- cv.sparsegl(
  x = X,
  y = y,
  group = groups, 
  weights = weights,
  family = stats::poisson(),
  intercept = TRUE,  
  nfolds = 5,
  pred.loss = "deviance"
)
```

I get the following error message:
```
Error in model.frame.default(formula = y ~ 1, weights = weights, offset = offset,  : 
  variable lengths differ (found for '(weights)')
```
I get the same error when using offsets instead of weights. 

There is an issue in the CV function: the weights/offsets are not subsetted in line 93-96 in `cv.R`. This should be fixable, I tried it in my fork: https://github.com/dajmcdon/sparsegl/compare/main...nizimmer:sparsegl:main

Another (potential) problem regarding observation weights occurs in the calculation of the CV metrics. At a first glance it seems that they are not considered in the calculation of `cvm` (line 216 and before in `cv.R`)?

Best regards
Nicolas

**Comment by dajmcdon** [comment]
Hi Nicolas,

Sorry, I'm just seeing this now. Thanks for using the package and for clearly explaining the issue. I'll try to fix this in the next few weeks.
